version: '3.4'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: file_service_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  fileservice:
    image: file_service:0.0.1
    ports:
      - "5001:5001"
    environment:
      - ConnectionStrings_DefaultConnection=Server=mysql;Database=file_service_db;User=root;Password=123456;
    depends_on:
      - mysql

volumes: 
  mysql_data: